version: 2
updates:
- package-ecosystem: npm
  directory: "/server"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  target-branch: dev
  ignore:
  - dependency-name: urijs
    versions:
    - 1.19.5
